name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ﾑ［ake test
      run: mkdir build && cd build && ﾑ［ake .. && make && cd ..
    - name: cd sys
      run: cd kinda_system
    - name: ﾑ［ake sys
      run: mkdir build && cd build && ﾑ［ake .. && make && cd ..
