name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt install cmake
    - name: cmake
      run: |
        mkdir build
        cd build
        sudo cmake ..
        sudo make
        cd ..
