name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ['examples/listeners_senders', 'examples/kinda_system', 'examples/highload_memory']

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt install cmake
    - name: cmake ${{ matrix.path }}
      working-directory: ${{ matrix.path }}
      run: |
        mkdir build
        cd build
        sudo cmake ..
        sudo make
        cd ..
