name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt install cmake
    - name: ﾑ［ake test
      run: |
        mkdir build 
        cd build
        sudo ﾑ［ake .. 
        sudo make 
        cd ..
    - name: cd sys
      run: cd kinda_system
    - name: ﾑ［ake sys
      run: |
        mkdir build
        cd build
        sudo ﾑ［ake .. 
        sudo make
